# Generated by Django 5.2.6 on 2025-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('mensagem_padrao', models.TextField(blank=True, null=True)),
                ('enviar_automatico', models.BooleanField(default=False)),
                ('notificacoes', models.BooleanField(default=True)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=10)),
            ],
        ),
    ]
