# Generated by Django 5.2.6 on 2025-09-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0003_rename_amount_pixtransaction_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixtransaction',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='link_pix',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
