# Generated by Django 5.2.6 on 2025-09-25 19:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('numero_cliente', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tipo_midia', models.CharField(blank=True, max_length=20, null=True)),
                ('link_pix', models.URLField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('erro', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
