# Generated by Django 5.2.6 on 2025-09-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatscustom',
            name='tipo_midia',
            field=models.CharField(blank=True, choices=[('--------', '--------'), ('TEXT', 'Texto'), ('IMAGEM', 'Imagem')], default='--------', max_length=20, null=True),
        ),
    ]
