# Generated by Django 5.2.6 on 2025-09-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_whatscustom_tipo_midia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatscustom',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendente'), ('SENT', 'Enviada'), ('DELIVERED', 'Entregue'), ('READ', 'Lida'), ('ERROR', 'Erro')], default='PENDING', max_length=50, null=True),
        ),
    ]
