# Generated by Django 5.2.6 on 2025-09-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_whatscustom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatscustom',
            name='tipo_midia',
            field=models.CharField(choices=[('--------', '--------'), ('TEXT', 'Texto'), ('IMAGEM', 'Imagem')], default='--------', max_length=20),
        ),
    ]
