# Generated by Django 5.2.6 on 2025-09-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_whatscustom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatscustom',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='static/covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='whatscustom',
            name='msg_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
