# Generated by Django 5.2.6 on 2025-09-25 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatscustom_cover_whatscustom_msg_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatscustom',
            name='numero_cliente',
            field=models.CharField(help_text='Digite apenas números', max_length=15, validators=[django.core.validators.RegexValidator(message='O número deve conter apenas dígitos.', regex='^\\d+$')]),
        ),
    ]
