# Generated by Django 5.2.6 on 2025-09-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_alter_whatscustom_numero_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatscustom',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whatscustom',
            name='oberservacao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whatscustom',
            name='status_cliente',
            field=models.CharField(blank=True, default='--------', max_length=255),
        ),
    ]
