# Generated by Django 5.2.6 on 2025-09-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatscustom_email_whatscustom_oberservacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatscustom',
            old_name='oberservacao',
            new_name='observacao',
        ),
    ]
