# Generated by Django 5.2.6 on 2025-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_rename_oberservacao_whatscustom_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatscustom',
            name='status_cliente',
            field=models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='whatscustom',
            name='tipo_midia',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('IMAGEM', 'Imagem')], default='--------', max_length=20),
        ),
    ]
