# Generated by Django 5.2.6 on 2025-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_alter_whatscustom_status_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatscustom',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='static/file/%Y/%m/%d/'),
        ),
    ]
